language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=false
sudo: required

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder"; Pkg.build()'

script:
  - julia build_tarballs.jl

deploy:
  provider: releases
  api_key:
    secure: N9nlSfS3exJKNm5dn8plJ4Yz39JWbQDDkIK5M4zUuepr/dF9jsy78rkrA46XXGW8A5NkaEoV8e/oTQgDXpTYr7lFQYwrQro0de4XBcik5Gv6wmNPT7yxjlFRjdYqblW1UeTmYr7xxOMcjgZENHHQYCoiOUf7i2LcooFTjPrjBMyJd+o3/nUEKiBuY93dsWhxBiD4s8Qy7CRvemw10d/shSPrdr+GOkiEoz+GWdSXEb6uZbAgTMEyMY9RGeJz9RGTnVXz4fY6RftaZHdSp+71GZ/8stRz7bKYInjVA2oNMHNQxbAn8JhAtGVKIw0Cq5nf9+MS9EcdR+36cSW7VpH/dK6Pa1O2p/f6rjn8p26832Zwh8aa4CX8e95KZ6OWgX29HCNL4NxYVux99xJuv8PDP8UxfMxybW3jjYF423rwoD3dT0+ij/f6JmSEQhRLCZJGUSId7dgkOFCCUgSeCik2zhN8Abk4QP9Toh3CxnMkzsNgs0yjHF1v3NFMWs7iWo4049odH1PKhQKVMn+DafXAU02R9X7pwiUh0rtWEbjbaO6AGJtP6me6TcxRzhAQQkXkX2TMfXGt1qGWyoyCb260BPvAo5vk3qIsIzAhlKdtfVKiia8DvsyZ2Y3qvZ26PLx+YBA0k2rZAJ6cenc3f2FtvGpy37sYTqd1GX2cbKXaaBY=
    
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: yukota/FluidSynthBuilder
    tags: true
