language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_AUTOMATIC_APPLE=false
sudo: required

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder"; Pkg.build()'

script:
  - julia build_tarballs.jl

deploy:
  provider: releases
  api_key:
    secure: "hTU9KGNGVzhzqJQV34FL7jCGZa1/7v8ShJfBvM2RfqZO5fFOyZwib2T8iELWdwOUYJcCG/ea24z8Tc4nh99Pzs2tFKnWKH1Nmyabs1FS6sry2OB+IAMV6oWA/5oBusaoG/cYCnwXhE1AOxkiL4DJkRGHpjukCTaTLK1V6vNcPed21kr6mPpb6cVL3t8ebCEh7vTkYhXaGoojnzOlC5P377imeg727FfZZF6SYWjEDwMjWsPaSJHOkcIpFBG19yZKSQJCLfhu7e14fv44GPzJF50bi7RZG/bkwTNuG5Kmbhy6fFlCOXUAcp1TOI0L1ZM+5nSeZO49x5KnYRyALdyZiNyy675wrK5JQm146ZRWmqFvdfzzLPKaOmg+YDE/yALAaMYeI8hfjZS5FavAMAPHxqNPmLQAg0exmTF3ghMVQEkLOsC9F72EaMJUn8f4cErHje2zNCPTrC1F9ci9tz2g+cFntMsAYSG/JDbFpLQ7W/umOFSUaN3RSb+rhVKlnyI8LYf+tbL0lH2XqT/cptFPKLIhu7BLURurVHB5bYw2WHqCGBhQowKPeRB5tL0hvNWFTa6O8vTf/dLJx6wqmTQAiFyl1zlWptTcf/Awb+LLFSm8rdf75nMRQ7A07QmbuciqVleZK19ZfSDk2vNPcnUUZLL3CdsftmTu9DEbf+70DFQ="

  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: yukota/FluidSynthBuilder
    tags: true
